apiVersion: apps/v1
kind: Deployment
metadata:  
  name: nodejs-deployment  
  labels:    
    app: node-app
spec:  
  replicas: 1  
  selector:    
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec: 
     containers:
      - name: node-app
        image: pareshbarad1992/node-app
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: node-app
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32121
  selector:
    app: node-app